const ACTION_TYPES = {
    SIDEBAR: {
        SEARCH_CLICKED: 'SEARCH_CLICKED',
        SEARCH_STARTED: 'SEARCH_STARTED',
        SEARCH_INPUT: 'SEARCH_INPUT',
        SEARCH_ERROR: 'SEARCH_ERROR',
        CLEAR_SEARCH: 'CLEAR_SEARCH',
        SEARCH_FINISHED: 'SEARCH_FINISHED',
        FAV_CLICKED: 'FAV_CLICKED',
        TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
        SELECTION: 'SELECTION',
        UNSELECT: 'UNSELECT'
    },
    WINDOW: {
        MINIMIZE: 'MINIMIZE',
        MAXIMIZE: 'MAXIMIZE',
        RESTORE: 'RESTORE',
        CLOSE: 'CLOSE',
        TOGGLE_COMPACT: 'TOGGLE_COMPACT',
        STATE_EXPANDED: 'STATE_EXPANDED',
        STATE_FULL_VIEW: 'STATE_FULL_VIEW'
    }
};

module.exports = ACTION_TYPES;
