export const SIDEBAR = {
    SEARCH_CLICKED: 'SEARCH_CLICKED',
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_INPUT: 'SEARCH_INPUT',
    SEARCH_ERROR: 'SEARCH_ERROR',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    SEARCH_FINISHED: 'SEARCH_FINISHED',
    FAV_CLICKED: 'FAV_CLICKED',
    INSERT_FAVOURITE_AT: 'INSERT_FAVOURITE_AT',
    TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
    SELECTION: 'SELECTION',
    UNSELECT: 'UNSELECT',
    QUANDL_RESPONSE: 'QUANDL_RESPONSE'
};

export const WINDOW = {
    MINIMIZE: 'MINIMIZE',
    MAXIMIZE: 'MAXIMIZE',
    RESTORE: 'RESTORE',
    CLOSE: 'CLOSE',
    OPEN: 'OPEN',
    TOGGLE_COMPACT: 'TOGGLE_COMPACT',
    STATE_EXPANDED: 'STATE_EXPANDED',
    STATE_FULL_VIEW: 'STATE_FULL_VIEW',
    RESIZING: 'RESIZING',
    RESIZE_ERROR: 'RESIZE_ERROR',
    UPDATING_OPTIONS: 'UPDATING_OPTIONS',
    UPDATING_OPTIONS_SUCCESS: 'UPDATING_OPTIONS_SUCCESS',
    UPDATING_OPTIONS_ERROR: 'UPDATING_OPTIONS_ERROR'
};
