export const SIDEBAR = {
    SEARCH_CLICKED: 'CHILD_SEARCH_CLICKED',
    SEARCH_STARTED: 'CHILD_SEARCH_STARTED',
    SEARCH_INPUT: 'CHILD_SEARCH_INPUT',
    SEARCH_ERROR: 'CHILD_SEARCH_ERROR',
    CLEAR_SEARCH: 'CHILD_CLEAR_SEARCH',
    SEARCH_FINISHED: 'CHILD_SEARCH_FINISHED',
    FAV_CLICKED: 'CHILD_FAV_CLICKED',
    INSERT_FAVOURITE_AT: 'CHILD_INSERT_FAVOURITE_AT',
    TOGGLE_FAVOURITE: 'CHILD_TOGGLE_FAVOURITE',
    SELECTION: 'CHILD_SELECTION',
    UNSELECT: 'CHILD_UNSELECT',
    QUANDL_RESPONSE: 'CHILD_QUANDL_RESPONSE',
    DRAG_OUT: 'DRAG_OUT',           // Handled by parent
    DRAG_ACCEPT: 'DRAG_ACCEPT'      // Handled by parent
};

export const WINDOW = {
    MINIMIZE: 'CHILD_MINIMIZE',
    MAXIMIZE: 'CHILD_MAXIMIZE',
    RESTORE: 'CHILD_RESTORE',
    CLOSE: 'CLOSE',                 // Handled by parent
    OPEN: 'CHILD_OPEN',
    TOGGLE_COMPACT: 'CHILD_TOGGLE_COMPACT',
    STATE_EXPANDED: 'CHILD_STATE_EXPANDED',
    STATE_FULL_VIEW: 'CHILD_STATE_FULL_VIEW',
    RESIZING: 'CHILD_RESIZING',
    RESIZE_ERROR: 'CHILD_RESIZE_ERROR',
    UPDATING_OPTIONS: 'CHILD_UPDATING_OPTIONS',
    UPDATING_OPTIONS_SUCCESS: 'CHILD_UPDATING_OPTIONS_SUCCESS',
    UPDATING_OPTIONS_ERROR: 'CHILD_UPDATING_OPTIONS_ERROR'
};
