const ACTION_TYPES = {
    INITIALISE_STATE: 'INITIALISE_STATE',
    CHILD_CONNECT: 'CHILD_CONNECT',
    CHILD_CHANGE: 'CHILD_CHANGE',
    CHILD_CLOSED: 'CHILD_CLOSED'
};

module.exports = ACTION_TYPES;
